### ISSUE TITLE
Getting an AttributeError in Python 2.6 with sys.version_info.major

### ISSUE THREAD

**Issue by aaronlelevier** [dlon/html2markdown#2]
In Python 2.6 `sys.version_info` doesn't have a `major` attribute.

Here is the stack trace and output:

```
>>> import html2markdown
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/rally_jira_sync/venv/lib/python2.6/site-packages/html2markdown.py", line 10, in <module>
    if sys.version_info.major > 2:
AttributeError: 'tuple' object has no attribute 'major'
>>> import sys
>>> sys.version_info
(2, 6, 6, 'final', 0)
>>> sys.version_info.major
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
>>> dir(sys.version_info)
['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
```

The line in question could be changed from:

```python
if sys.version_info.major > 2:
```

To:

```python
if sys.version_info[0] > 2:
```

To support Python 2.6.  

Not sure how supported this library is, but just submitting the issue to see if I get a reply.

Thanks

**Comment by dlon** [comment]
Thanks. I added the change you suggested.

https://github.com/dlon/html2markdown/commit/24444fd1e6f360bdb0175e6bfb280607e43fe668

**Comment by aaronlelevier** [comment]
Great. Thank you.
